export const DEFAULTS = {
  pair: "EURUSD",
  timeframe: "H1",

  selectedModels: [] as string[],

  confidenceThreshold: 0.8,
  targetActiveRate: 0.15,
  targetCoverage: 0.15,
  calibrateMethod: "sigmoid" as const,
  evalUseTradingCosts: true,
  slipNormBps: 0.25,

  useTripleBarrier: true,
  tbPtMult: 2.0,
  tbSlMult: 2.0,
  tbNeutralZone: 0.5,
  tbMaxHolding: 36,
  labelThreshold: 0.0005,

  useAdx: true,
  useAtr: true,
  useBbands: true,
  useEma: true,
  useSma: true,
  useRsi: true,
  useMacd: true,
  useStoch: false,
  useSar: false,
  useDonchian: true,

  useFracdiff: true,
  fracdiffD: 0.4,
  useCrossoverBins: true,
  useMaSpread: false,
  usePriceMaZ: true,
  useIndicatorStates: false,

  lags: 14,
  lagDepth: 1,

  useMtfMa: true,
  useMtfAlignment: true,
  useMtfAlign: false,
  useMacdAtrRatio: true,
  useTripleConfirm: true,
  useTrendConfirm: true,
  useVolManagedMom: true,
  useVmMom: false,
  useSqueezeBreakout: false,
  useSqueezeExpansion: false,
  useAtrChannelBreakout: false,
  useExtAtrLowAdx: false,
  useReentryMom: false,
  useSlopeDiff: false,
  useRvFeatures: true,

  useNews: true,
  newsEventFlags: true,
  newsSentimentBackend: "vader" as const,

  llmSentimentEnabled: false,
  llmBackend: "ollama" as const,
  llmModel: "llama3",
  llmWeight: 0.7,
  llmApiKey: "",

  startDate: "" as string,
  endDate: "" as string,

  logitC: 1.0,
  logitSolver: "lbfgs" as const,
  logitPenalty: "l2" as const,
  logitMaxIter: 500,
  logitTol: 0.0001,

  nTrials: 10,
  optunaDirection: "maximize" as const,
  seed: 42,
  repeats: 1,

  trainMonths: 36,
  testMonths: 1,

  sizingMethod: "fixed" as const,
  riskFraction: 0.02,
  kellyFraction: 0.5,
  kellyMinTrades: 10,
  atrRiskPct: 0.02,
  atrSlMult: 2.0,
  initialEquity: 10000,
  maxLeverage: 5.0,

  maxDrawdownPct: 0.15,
  maxConsecutiveLosses: 5,
  dailyLossLimitPct: 0.03,

  trailingMethod: "none" as const,
  trailingActivation: 0.01,
} as const;

export const RANGES = {
  confidenceThreshold: { min: 0, max: 1, step: 0.05 },
  targetActiveRate: { min: 0.05, max: 0.3, step: 0.01 },
  targetCoverage: { min: 0.05, max: 0.3, step: 0.01 },
  slipNormBps: { min: 0, max: 2, step: 0.05 },
  tbPtMult: { min: 0.5, max: 4, step: 0.25 },
  tbSlMult: { min: 0.5, max: 4, step: 0.25 },
  tbNeutralZone: { min: 0, max: 2, step: 0.25 },
  tbMaxHolding: { min: 4, max: 72, step: 4 },
  labelThreshold: { min: 0.0001, max: 0.005, step: 0.0001 },
  fracdiffD: { min: 0, max: 1, step: 0.05 },
  lags: { min: 1, max: 60, step: 1 },
  lagDepth: { min: 1, max: 3, step: 1 },
  nTrials: { min: 0, max: 150, step: 1 },
  repeats: { min: 1, max: 10, step: 1 },
  seed: { min: 0, max: 9999, step: 1 },
  trainMonths: { min: 6, max: 60, step: 1 },
  testMonths: { min: 1, max: 6, step: 1 },
  riskFraction: { min: 0.005, max: 0.1, step: 0.005 },
  kellyFraction: { min: 0.1, max: 1.0, step: 0.1 },
  kellyMinTrades: { min: 5, max: 100, step: 5 },
  atrRiskPct: { min: 0.005, max: 0.05, step: 0.005 },
  atrSlMult: { min: 0.5, max: 5, step: 0.25 },
  initialEquity: { min: 1000, max: 100000, step: 1000 },
  maxLeverage: { min: 1, max: 50, step: 1 },
  maxDrawdownPct: { min: 0.05, max: 0.5, step: 0.05 },
  maxConsecutiveLosses: { min: 2, max: 20, step: 1 },
  dailyLossLimitPct: { min: 0.01, max: 0.1, step: 0.01 },
  trailingActivation: { min: 0, max: 0.05, step: 0.005 },
} as const;

export const SELECT_OPTIONS = {
  calibrateMethod: [
    { value: "sigmoid", label: "Sigmoid (Platt)" },
    { value: "isotonic", label: "Isotonic Regression" },
  ],
  logitSolver: [
    { value: "lbfgs", label: "L-BFGS" },
    { value: "newton-cg", label: "Newton-CG" },
    { value: "sag", label: "SAG" },
    { value: "saga", label: "SAGA" },
    { value: "liblinear", label: "LibLinear" },
  ],
  logitPenalty: [
    { value: "l2", label: "L2 (Ridge)" },
    { value: "l1", label: "L1 (Lasso)" },
    { value: "elasticnet", label: "ElasticNet" },
    { value: "none", label: "None" },
  ],
  optunaDirection: [
    { value: "maximize", label: "Maximize" },
    { value: "minimize", label: "Minimize" },
  ],
  sizingMethod: [
    { value: "fixed", label: "Fixed Lot" },
    { value: "kelly", label: "Kelly Criterion" },
    { value: "fixed_fractional", label: "Fixed Fractional" },
    { value: "atr", label: "ATR-Based" },
  ],
  trailingMethod: [
    { value: "none", label: "None" },
    { value: "standard", label: "Standard (Fixed Pips)" },
    { value: "atr", label: "ATR Trailing" },
    { value: "chandelier", label: "Chandelier Exit" },
  ],
  newsSentimentBackend: [
    { value: "vader", label: "VADER (Rule-based)" },
    { value: "finbert", label: "finBERT (Neural)" },
  ],
  llmBackend: [
    { value: "ollama", label: "Ollama (Local, Free)" },
    { value: "openai", label: "OpenAI API" },
    { value: "anthropic", label: "Anthropic API" },
  ],
  hpoIntensity: [
    { value: "light", label: "Light (1+1 trials)" },
    { value: "quick", label: "Quick (2+2 trials)" },
    { value: "standard", label: "Standard (per-model tuned)" },
    { value: "deep", label: "Deep (max trials)" },
  ],
} as const;

export const TIMEFRAMES = [
  { key: "M15", label: "M15" },
  { key: "M30", label: "M30" },
  { key: "H1", label: "H1" },
  { key: "H2", label: "H2" },
  { key: "H4", label: "H4" },
];

export const STUDY_PRESETS = {
  diagnostic: {
    key: "diagnostic",
    label: "Diagnostic",
    badge: "Smoke",
    badgeColor: "green",
    hpoIntensity: "light" as const,
    trialRange: { min: 10, max: 10 },
    repeats: 1,
    trainMonths: 24,
    testMonths: 1,
    confidenceThreshold: 0.7,
    targetActiveRate: 0.1,
    targetCoverage: 0.1,
    description: "Quick pipeline check. 10 trials per model, 1 run. Floor minimum — not statistically meaningful.",
    estMinutes: { logistic: 2, xgboost: 3, svm: 3, random_forest: 4, decision_tree: 2, lstm: 5, cnn: 4, transformer: 6 },
  },
  exploratory: {
    key: "exploratory",
    label: "Exploratory",
    badge: "Signal",
    badgeColor: "yellow",
    hpoIntensity: "standard" as const,
    trialRange: { min: 10, max: 20 },
    repeats: 3,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.8,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Detects seed-dependent strategies. 10-20 trials per model × 3 runs.",
    estMinutes: { logistic: 15, xgboost: 30, svm: 20, random_forest: 35, decision_tree: 10, lstm: 60, cnn: 45, transformer: 90 },
  },
  validation: {
    key: "validation",
    label: "Validation",
    badge: "Research",
    badgeColor: "orange",
    hpoIntensity: "deep" as const,
    trialRange: { min: 10, max: 40 },
    repeats: 5,
    trainMonths: 48,
    testMonths: 1,
    confidenceThreshold: 0.85,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Median-of-5 robustness. 10-40 trials per model × 5 runs — model-aware budgets.",
    estMinutes: { logistic: 45, xgboost: 90, svm: 60, random_forest: 100, decision_tree: 30, lstm: 180, cnn: 140, transformer: 240 },
  },
  production: {
    key: "production",
    label: "Production",
    badge: "Deploy",
    badgeColor: "red",
    hpoIntensity: "deep" as const,
    trialRange: { min: 10, max: 40 },
    repeats: 10,
    trainMonths: 60,
    testMonths: 1,
    confidenceThreshold: 0.9,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Maximum statistical rigor. 10-40 trials per model × 10 runs. Decile confidence bands.",
    estMinutes: { logistic: 120, xgboost: 240, svm: 160, random_forest: 280, decision_tree: 80, lstm: 480, cnn: 360, transformer: 600 },
  },
} as const;

export const QUICK_START_CATEGORIES = [
  {
    key: "debug",
    label: "Smoke Tests",
    icon: "bug",
    options: [
      {
        key: "baseline",
        label: "Logistic Probe",
        subtitle: "Runs the full pipeline with a single Logistic model and minimal HPO. Use this to confirm data, features, and labels are wired correctly before committing compute.",
        models: ["logistic"],
        hpoIntensity: "light" as const,
        nTrials: 10,
        repeats: 1,
        trainMonths: 12,
        testMonths: 1,
        confidenceThreshold: 0.7,
        estMinutes: 2,
      },
      {
        key: "signal",
        label: "XGBoost Smoke",
        subtitle: "Fast XGBoost run to surface any signal before tuning. 20 Optuna trials on 2 years of data — enough to reject pure noise, not enough to trust.",
        models: ["xgboost"],
        hpoIntensity: "quick" as const,
        nTrials: 20,
        repeats: 1,
        trainMonths: 24,
        testMonths: 1,
        confidenceThreshold: 0.75,
        estMinutes: 8,
      },
    ],
  },
  {
    key: "classical",
    label: "Classical Models",
    icon: "cpu",
    options: [
      {
        key: "classical_logit",
        label: "Logistic Regression",
        subtitle: "Ridge-penalised Logistic on 3 years of data. Cheap, interpretable, and a solid coefficient-based baseline. Good first stop when you want to understand which features matter.",
        models: ["logistic"],
        hpoIntensity: "standard" as const,
        nTrials: 30,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.8,
        estMinutes: 15,
      },
      {
        key: "classical_tri",
        label: "Logit + SVM + XGBoost",
        subtitle: "Three complementary classifiers in one run: linear boundary (Logit), margin-maximising kernel (SVM), and gradient-boosted trees (XGBoost). Compare Sharpe across them directly.",
        models: ["logistic", "svm", "xgboost"],
        hpoIntensity: "standard" as const,
        nTrials: 50,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.8,
        estMinutes: 45,
      },
      {
        key: "classical_full",
        label: "Full Classical Suite",
        subtitle: "All five classical models — Logit, SVM, Decision Tree, Random Forest, XGBoost — at 80 trials each. Use this to benchmark every traditional approach before moving to deep learning.",
        models: ["logistic", "svm", "decision_tree", "random_forest", "xgboost"],
        hpoIntensity: "standard" as const,
        nTrials: 80,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.85,
        estMinutes: 120,
      },
      {
        key: "classical_hardened",
        label: "Hardened Classical",
        subtitle: "Same five models at deep HPO depth (120 trials) on 4 years of training data. Higher confidence threshold filters marginal signals. The deployment-ready classical benchmark.",
        models: ["logistic", "svm", "decision_tree", "random_forest", "xgboost"],
        hpoIntensity: "deep" as const,
        nTrials: 120,
        repeats: 1,
        trainMonths: 48,
        testMonths: 1,
        confidenceThreshold: 0.85,
        estMinutes: 240,
      },
    ],
  },
  {
    key: "deep",
    label: "Deep Learning",
    icon: "network",
    options: [
      {
        key: "deep_lstm_solo",
        label: "LSTM Sequence",
        subtitle: "Single LSTM on 3 years of data. Tests whether temporal ordering in your feature lags adds predictive value over classical approaches. 40 Optuna trials.",
        models: ["lstm"],
        hpoIntensity: "standard" as const,
        nTrials: 40,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.8,
        estMinutes: 60,
      },
      {
        key: "deep_cnn_lstm",
        label: "CNN + LSTM Pair",
        subtitle: "CNN captures local price patterns, LSTM tracks sequential dependencies. Running both reveals whether spatial or temporal structure drives your edge — 60 trials each.",
        models: ["lstm", "cnn"],
        hpoIntensity: "standard" as const,
        nTrials: 60,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.8,
        estMinutes: 150,
      },
      {
        key: "deep_full_stack",
        label: "CNN + LSTM + Transformer",
        subtitle: "Full deep learning stack at maximum depth. CNN for patterns, LSTM for memory, Transformer for global attention across the lag window. 100 trials each, 4-year training set.",
        models: ["cnn", "lstm", "transformer"],
        hpoIntensity: "deep" as const,
        nTrials: 100,
        repeats: 1,
        trainMonths: 48,
        testMonths: 1,
        confidenceThreshold: 0.85,
        estMinutes: 360,
      },
    ],
  },
  {
    key: "ensemble",
    label: "Ensemble Models",
    icon: "layers",
    options: [
      {
        key: "ensemble_regime",
        label: "Adaptive Regime",
        subtitle: "RF-based regime detector routes predictions to context-specific sub-models. Tests whether your data has distinct trending, ranging, and volatile states worth separating.",
        models: ["ensemble_adaptive_regime"],
        hpoIntensity: "standard" as const,
        nTrials: 30,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.85,
        estMinutes: 60,
      },
      {
        key: "ensemble_hybrid",
        label: "CNN-LSTM-XGB Fusion",
        subtitle: "Stacks CNN pattern detection, LSTM memory, and XGBoost tabular strength into a single ensemble signal. 50 trials each. Best for capturing multi-structure edges.",
        models: ["ensemble_cnn_lstm_xgboost"],
        hpoIntensity: "standard" as const,
        nTrials: 50,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.85,
        estMinutes: 180,
      },
      {
        key: "ensemble_full",
        label: "Both Ensembles, Deep HPO",
        subtitle: "Adaptive Regime and CNN-LSTM-XGB run back-to-back at deep HPO on 4 years of data. The most complete ensemble benchmark — use when you want to deploy an ensemble strategy.",
        models: ["ensemble_adaptive_regime", "ensemble_cnn_lstm_xgboost"],
        hpoIntensity: "deep" as const,
        nTrials: 80,
        repeats: 1,
        trainMonths: 48,
        testMonths: 1,
        confidenceThreshold: 0.9,
        estMinutes: 360,
      },
    ],
  },
  {
    key: "rl",
    label: "Reinforcement Learning",
    icon: "bot",
    options: [
      {
        key: "rl_dqn_explore",
        label: "DQN Exploration",
        subtitle: "Short DQN run to test whether a learned action policy outperforms random entry on your data. 20 trials, 2-year window. Treat this as a feasibility check, not a deployable strategy.",
        models: ["dqn"],
        hpoIntensity: "standard" as const,
        nTrials: 20,
        repeats: 1,
        trainMonths: 24,
        testMonths: 1,
        confidenceThreshold: 0.7,
        estMinutes: 30,
      },
      {
        key: "rl_dqn_tuned",
        label: "DQN Tuned Policy",
        subtitle: "50 deep HPO trials on 3 years of data. Optimises replay buffer, learning rate, network depth, and epsilon decay jointly. Use this to compare a tuned RL policy against your best classical model.",
        models: ["dqn"],
        hpoIntensity: "deep" as const,
        nTrials: 50,
        repeats: 1,
        trainMonths: 36,
        testMonths: 1,
        confidenceThreshold: 0.8,
        estMinutes: 90,
      },
    ],
  },
];

export const MODEL_CONSTRAINTS: Record<string, { rules: string[]; tips: string[] }> = {
  logistic: {
    rules: ["VIF > 10 may cause unstable coefficients — check Training Diagnostics after backtest."],
    tips: ["C in range 0.01–100 (log scale). Higher C = less regularization, may overfit.", "Use 'balanced' class_weight for imbalanced labels (default)."],
  },
  svm: {
    rules: ["Gamma is now categorical [0.0001, 0.001, 0.01, 0.1, 0.5] — no more gamma=10 that memorizes noise.", "Permutation importance is model-agnostic. Trust it less than SHAP for tree models."],
    tips: ["RBF kernel is fixed — best for non-linear FX patterns.", "Higher gamma = more localized decision boundaries = risk of overfitting."],
  },
  random_forest: {
    rules: ["max_depth has no None option — trees are always depth-bounded to prevent perfect IS fit.", "Feature importance uses SHAP (gold standard) when available, else MDI (biased — prefer SHAP)."],
    tips: ["n_estimators 300–1000 (step 100). More trees = smoother predictions.", "min_samples_leaf 1–10. Higher = less overfitting."],
  },
  xgboost: {
    rules: ["Feature importance uses TreeSHAP — exact Shapley values.", "n_trials floor is 10 even in light HPO mode."],
    tips: ["Learning rate 0.01–0.3 (log scale). Lower LR needs more trees.", "max_depth 3–8. Shallower trees generalize better on financial data.", "subsample 0.6–1.0 helps prevent overfitting to noise."],
  },
  decision_tree: {
    rules: ["Single tree — highly interpretable but prone to overfitting. Use for feature analysis, not production."],
    tips: ["Compare its feature importance to XGBoost's — agreement suggests robust features."],
  },
  lstm: {
    rules: ["units / lags ratio: optimal 1.5–2.5. At ratio >5, model likely memorizes noise.", "lr in range 1e-4 to 5e-3 (log scale)."],
    tips: ["Start with 32–64 units for 14 lags. Increase lags before increasing units.", "Use early stopping — patience=6 avoids overtraining on small validation sets."],
  },
  cnn: {
    rules: ["lags ≥ kernel_size × layers (receptive field). 3 layers × kernel=3 = 7 bars seen. With lags=14, only last 7 matter — earlier lags are wasted compute.", "lr in range 1e-4 to 5e-3 (log scale)."],
    tips: ["filters 32/64/96. More filters = more pattern detectors.", "Kernel size 3 or 5. Larger kernels see more bars per scan."],
  },
  transformer: {
    rules: ["d_model must be divisible by num_heads. d_model/num_heads ≥ 8 (e.g., 64/4=16 ✓, 32/8=4 ✗).", "Attention weights are NOT feature importance. Trust gradient-based rankings over raw attention."],
    tips: ["d_model 32/64/128. Larger = more capacity but slower training.", "dropout 0.1–0.4. Higher dropout for smaller datasets."],
  },
  dqn: {
    rules: ["Very slow per trial (~2.5 min). Use Minimal preset for quick tests.", "Requires GPU for reasonable runtime on deep architectures."],
    tips: ["Start with fewer episodes for validation, then scale up.", "DQN is the only RL model — use it to compare learned policies vs supervised approaches."],
  },
  ensemble_adaptive_regime: {
    rules: ["Delegates to sub-models (RF for regime detection, XGBoost for prediction). Feature importance comes from sub-model.", "GPU recommended — sub-models train sequentially but may use GPU internally."],
    tips: ["Best for mixed-regime markets (sideways + trending + volatile).", "Start with Minimal preset (30 trials) to test regime detection quality."],
  },
  ensemble_cnn_lstm_xgboost: {
    rules: ["Combines CNN (pattern detection), LSTM (sequential memory), and XGBoost (tabular strength).", "Very slow per trial (~3 min). GPU strongly recommended."],
    tips: ["Feature importance extracted from XGBoost sub-model via TreeSHAP.", "Use Production preset only when you've validated component models individually."],
  },
};
