export const DEFAULTS = {
  pair: "EURUSD",
  timeframe: "H1",

  selectedModels: [] as string[],

  confidenceThreshold: 0.8,
  targetActiveRate: 0.15,
  targetCoverage: 0.15,
  calibrateMethod: "sigmoid" as const,
  evalUseTradingCosts: true,
  slipNormBps: 0.25,

  useTripleBarrier: true,
  tbPtMult: 2.0,
  tbSlMult: 2.0,
  tbNeutralZone: 0.5,
  tbMaxHolding: 36,
  labelThreshold: 0.0005,

  useAdx: true,
  useAtr: true,
  useBbands: true,
  useEma: true,
  useSma: true,
  useRsi: true,
  useMacd: true,
  useStoch: false,
  useSar: false,
  useDonchian: true,

  useFracdiff: true,
  fracdiffD: 0.4,
  useCrossoverBins: true,
  useMaSpread: false,
  usePriceMaZ: true,
  useIndicatorStates: false,

  lags: 14,
  lagDepth: 1,

  useMtfMa: true,
  useMtfAlignment: true,
  useMtfAlign: false,
  useMacdAtrRatio: true,
  useTripleConfirm: true,
  useTrendConfirm: true,
  useVolManagedMom: true,
  useVmMom: false,
  useSqueezeBreakout: false,
  useSqueezeExpansion: false,
  useAtrChannelBreakout: false,
  useExtAtrLowAdx: false,
  useReentryMom: false,
  useSlopeDiff: false,
  useRvFeatures: true,

  useNews: true,
  newsEventFlags: true,
  newsSentimentBackend: "vader" as const,

  llmSentimentEnabled: false,
  llmBackend: "ollama" as const,
  llmModel: "llama3",
  llmWeight: 0.7,
  llmApiKey: "",

  startDate: "" as string,
  endDate: "" as string,

  logitC: 1.0,
  logitSolver: "lbfgs" as const,
  logitPenalty: "l2" as const,
  logitMaxIter: 500,
  logitTol: 0.0001,

  nTrials: 10,
  optunaDirection: "maximize" as const,
  seed: 42,
  repeats: 1,

  trainMonths: 36,
  testMonths: 1,

  sizingMethod: "fixed" as const,
  riskFraction: 0.02,
  kellyFraction: 0.5,
  kellyMinTrades: 10,
  atrRiskPct: 0.02,
  atrSlMult: 2.0,
  initialEquity: 10000,
  maxLeverage: 5.0,

  maxDrawdownPct: 0.15,
  maxConsecutiveLosses: 5,
  dailyLossLimitPct: 0.03,

  trailingMethod: "none" as const,
  trailingActivation: 0.01,
} as const;

export const RANGES = {
  confidenceThreshold: { min: 0, max: 1, step: 0.05 },
  targetActiveRate: { min: 0.05, max: 0.3, step: 0.01 },
  targetCoverage: { min: 0.05, max: 0.3, step: 0.01 },
  slipNormBps: { min: 0, max: 2, step: 0.05 },
  tbPtMult: { min: 0.5, max: 4, step: 0.25 },
  tbSlMult: { min: 0.5, max: 4, step: 0.25 },
  tbNeutralZone: { min: 0, max: 2, step: 0.25 },
  tbMaxHolding: { min: 4, max: 72, step: 4 },
  labelThreshold: { min: 0.0001, max: 0.005, step: 0.0001 },
  fracdiffD: { min: 0, max: 1, step: 0.05 },
  lags: { min: 1, max: 60, step: 1 },
  lagDepth: { min: 1, max: 3, step: 1 },
  nTrials: { min: 2, max: 100, step: 1 },
  repeats: { min: 1, max: 10, step: 1 },
  seed: { min: 0, max: 9999, step: 1 },
  trainMonths: { min: 6, max: 60, step: 1 },
  testMonths: { min: 1, max: 6, step: 1 },
  riskFraction: { min: 0.005, max: 0.1, step: 0.005 },
  kellyFraction: { min: 0.1, max: 1.0, step: 0.1 },
  kellyMinTrades: { min: 5, max: 100, step: 5 },
  atrRiskPct: { min: 0.005, max: 0.05, step: 0.005 },
  atrSlMult: { min: 0.5, max: 5, step: 0.25 },
  initialEquity: { min: 1000, max: 100000, step: 1000 },
  maxLeverage: { min: 1, max: 50, step: 1 },
  maxDrawdownPct: { min: 0.05, max: 0.5, step: 0.05 },
  maxConsecutiveLosses: { min: 2, max: 20, step: 1 },
  dailyLossLimitPct: { min: 0.01, max: 0.1, step: 0.01 },
  trailingActivation: { min: 0, max: 0.05, step: 0.005 },
} as const;

export const SELECT_OPTIONS = {
  calibrateMethod: [
    { value: "sigmoid", label: "Sigmoid (Platt)" },
    { value: "isotonic", label: "Isotonic Regression" },
  ],
  logitSolver: [
    { value: "lbfgs", label: "L-BFGS" },
    { value: "newton-cg", label: "Newton-CG" },
    { value: "sag", label: "SAG" },
    { value: "saga", label: "SAGA" },
    { value: "liblinear", label: "LibLinear" },
  ],
  logitPenalty: [
    { value: "l2", label: "L2 (Ridge)" },
    { value: "l1", label: "L1 (Lasso)" },
    { value: "elasticnet", label: "ElasticNet" },
    { value: "none", label: "None" },
  ],
  optunaDirection: [
    { value: "maximize", label: "Maximize" },
    { value: "minimize", label: "Minimize" },
  ],
  sizingMethod: [
    { value: "fixed", label: "Fixed Lot" },
    { value: "kelly", label: "Kelly Criterion" },
    { value: "fixed_fractional", label: "Fixed Fractional" },
    { value: "atr", label: "ATR-Based" },
  ],
  trailingMethod: [
    { value: "none", label: "None" },
    { value: "standard", label: "Standard (Fixed Pips)" },
    { value: "atr", label: "ATR Trailing" },
    { value: "chandelier", label: "Chandelier Exit" },
  ],
  newsSentimentBackend: [
    { value: "vader", label: "VADER (Rule-based)" },
    { value: "finbert", label: "finBERT (Neural)" },
  ],
  llmBackend: [
    { value: "ollama", label: "Ollama (Local, Free)" },
    { value: "openai", label: "OpenAI API" },
    { value: "anthropic", label: "Anthropic API" },
  ],
  hpoIntensity: [
    { value: "light", label: "Light (1+1 trials)" },
    { value: "quick", label: "Quick (2+2 trials)" },
    { value: "standard", label: "Standard (per-model tuned)" },
    { value: "deep", label: "Deep (max trials)" },
  ],
} as const;

export const TIMEFRAMES = [
  { key: "M15", label: "M15" },
  { key: "M30", label: "M30" },
  { key: "H1", label: "H1" },
  { key: "H2", label: "H2" },
  { key: "H4", label: "H4" },
];

export const STUDY_PRESETS = {
  diagnostic: {
    key: "diagnostic",
    label: "Diagnostic",
    badge: "Smoke",
    badgeColor: "green",
    hpoIntensity: "light" as const,
    trialRange: { min: 10, max: 10 },
    repeats: 1,
    trainMonths: 24,
    testMonths: 1,
    confidenceThreshold: 0.7,
    targetActiveRate: 0.1,
    targetCoverage: 0.1,
    description: "Quick pipeline check. 10 trials per model, 1 run. Floor minimum — not statistically meaningful.",
    estMinutes: { logistic: 2, xgboost: 3, svm: 3, random_forest: 4, decision_tree: 2, lstm: 5, cnn: 4, transformer: 6 },
  },
  exploratory: {
    key: "exploratory",
    label: "Exploratory",
    badge: "Signal",
    badgeColor: "yellow",
    hpoIntensity: "standard" as const,
    trialRange: { min: 10, max: 20 },
    repeats: 3,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.8,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Detects seed-dependent strategies. 10-20 trials per model × 3 runs.",
    estMinutes: { logistic: 15, xgboost: 30, svm: 20, random_forest: 35, decision_tree: 10, lstm: 60, cnn: 45, transformer: 90 },
  },
  validation: {
    key: "validation",
    label: "Validation",
    badge: "Research",
    badgeColor: "orange",
    hpoIntensity: "deep" as const,
    trialRange: { min: 10, max: 40 },
    repeats: 5,
    trainMonths: 48,
    testMonths: 1,
    confidenceThreshold: 0.85,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Median-of-5 robustness. 10-40 trials per model × 5 runs — model-aware budgets.",
    estMinutes: { logistic: 45, xgboost: 90, svm: 60, random_forest: 100, decision_tree: 30, lstm: 180, cnn: 140, transformer: 240 },
  },
  production: {
    key: "production",
    label: "Production",
    badge: "Deploy",
    badgeColor: "red",
    hpoIntensity: "deep" as const,
    trialRange: { min: 10, max: 40 },
    repeats: 10,
    trainMonths: 60,
    testMonths: 1,
    confidenceThreshold: 0.9,
    targetActiveRate: 0.15,
    targetCoverage: 0.15,
    description: "Maximum statistical rigor. 10-40 trials per model × 10 runs. Decile confidence bands.",
    estMinutes: { logistic: 120, xgboost: 240, svm: 160, random_forest: 280, decision_tree: 80, lstm: 480, cnn: 360, transformer: 600 },
  },
} as const;

export const QUICK_START_PRESETS = [
  {
    key: "baseline",
    label: "Baseline Check",
    subtitle: "Quick pipeline validation — is everything working?",
    models: ["logistic"],
    hpoIntensity: "light" as const,
    nTrials: 10,
    repeats: 1,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.7,
    estMinutes: 2,
  },
  {
    key: "classical",
    label: "Classical Suite",
    subtitle: "Compare all classical ML models on the same data.",
    models: ["logistic", "svm", "decision_tree", "random_forest", "xgboost"],
    hpoIntensity: "standard" as const,
    nTrials: 10,
    repeats: 1,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.8,
    estMinutes: 45,
  },
  {
    key: "deep",
    label: "Deep Comparison",
    subtitle: "Benchmark deep architectures for feature extraction.",
    models: ["cnn", "lstm", "transformer"],
    hpoIntensity: "standard" as const,
    nTrials: 10,
    repeats: 1,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.8,
    estMinutes: 180,
  },
  {
    key: "ensemble",
    label: "Ensemble Power",
    subtitle: "Production ensemble strategies for maximum robustness.",
    models: ["ensemble_adaptive_regime", "ensemble_cnn_lstm_xgboost"],
    hpoIntensity: "standard" as const,
    nTrials: 10,
    repeats: 1,
    trainMonths: 36,
    testMonths: 1,
    confidenceThreshold: 0.85,
    estMinutes: 120,
  },
  {
    key: "full",
    label: "Full Grid",
    subtitle: "Exhaustive comparison across all 10 model types.",
    models: ["logistic", "svm", "decision_tree", "random_forest", "xgboost", "cnn", "lstm", "transformer", "dqn", "ensemble_adaptive_regime", "ensemble_cnn_lstm_xgboost"],
    hpoIntensity: "deep" as const,
    nTrials: 20,
    repeats: 1,
    trainMonths: 48,
    testMonths: 1,
    confidenceThreshold: 0.85,
    estMinutes: 480,
  },
  {
    key: "signal",
    label: "Quick Signal",
    subtitle: "Fast check — is there any tradeable signal?",
    models: ["xgboost"],
    hpoIntensity: "quick" as const,
    nTrials: 10,
    repeats: 1,
    trainMonths: 24,
    testMonths: 1,
    confidenceThreshold: 0.75,
    estMinutes: 5,
  },
];
